# Generated by Django 2.2.1 on 2019-06-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_group_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='num_members',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
